# Generated by Django 3.1.3 on 2021-07-19 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_directory_path, verbose_name='avatar')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='code')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربران',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_image', models.ImageField(blank=True, null=True, upload_to=users.models.user_identifier_image_directory_path, verbose_name='عکس احراز هویت')),
                ('request_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان درخواست')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان ابطال')),
                ('status', models.CharField(choices=[('2', 'احراز شده'), ('1', 'درخواست احراز'), ('3', 'احراز نشده')], default='3', max_length=1, verbose_name='وضعیت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'احراز هویت',
                'verbose_name_plural': 'احراز هویت',
                'ordering': ['-request_time'],
            },
        ),
    ]
