# Generated by Django 3.1.3 on 2021-07-19 13:27

import django.core.validators
from django.db import migrations, models
import ticketing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'ادمین',
                'verbose_name_plural': 'ادمین ها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachmentfile', models.FileField(help_text='حداکثر سایز عکس باید 2.0\xa0MB باشد', upload_to=ticketing.models.user_files_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'zip', 'rar', 'mp4', 'mkv']), ticketing.models.validate_file_size], verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='امتیاز')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('text', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='به جای حذف زیر بخش، این گزینه را غیر فعال کنید', verbose_name='فعال')),
                ('avatar', models.FileField(blank=True, help_text='حداکثر سایز عکس باید 409.6\xa0KB باشد', null=True, upload_to=ticketing.models.section_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), ticketing.models.validate_image_size], verbose_name='آواتار')),
            ],
            options={
                'verbose_name': 'زیر بخش',
                'verbose_name_plural': 'زیر بخش ها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('status', models.CharField(choices=[('1', 'در انتظار پاسخ'), ('2', 'در حال بررسی'), ('3', 'پاسخ داده شده'), ('4', 'بسته شده')], default='1', max_length=1, verbose_name='وضعیت')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین تغییرات')),
                ('priority', models.CharField(choices=[('3', 'اولویت زیاد'), ('2', 'اولویت متوسط'), ('1', 'اولویت کم')], max_length=1, verbose_name='اولویت')),
                ('tags', models.TextField(blank=True, default='', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'تاریخچه تیکت',
                'verbose_name_plural': 'تاریخچه تیکت ها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='به جای حذف بخش، این گزینه را غیر فعال کنید', verbose_name='فعال')),
                ('avatar', models.FileField(blank=True, help_text='حداکثر سایز عکس باید 409.6\xa0KB باشد', null=True, upload_to=ticketing.models.topic_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), ticketing.models.validate_image_size], verbose_name='آواتار')),
                ('is_recommended', models.BooleanField(default=False, help_text='در صورت فعال بودن این گزینه آدرس بخش مورد نظر در صفحه اصلی نمایش داده خواهد شد', verbose_name='پیشنهادی')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش ها',
                'ordering': ['title'],
            },
        ),
    ]
