# Generated by Django 3.1.3 on 2021-07-19 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_topics', to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ticketing.admin', verbose_name='ادمین'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ادمین مسئول'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.section', verbose_name='زیر بخش'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.ticket', verbose_name='تیکت'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ticketing.admin', verbose_name='ادمین ها'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.section', verbose_name='زیر بخش مربوطه'),
        ),
        migrations.AddField(
            model_name='section',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ticketing.admin', verbose_name='گروه مسئولین این زیربخش'),
        ),
        migrations.AddField(
            model_name='section',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.topic', verbose_name='متعلق به بخش'),
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='تیکت مربوطه'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.message', verbose_name='پیام مربوطه'),
        ),
        migrations.AddField(
            model_name='admin',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='ticketing.topic'),
        ),
        migrations.AddField(
            model_name='admin',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='ادمین ها'),
        ),
    ]
