image: docker:stable

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - rm -rf /temp/*
    - cp -rT ./ /temp
    - docker-compose up -d --force-recreate
  tags:
    - KhuServer
  only:
    - production
